<?php

  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://ax.kisc.kz:8243/token');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=password&username=P0202044&password=Icredit2021!&scope=identkey");

$headers = array();
$headers[] = 'Authorization: Basic NVZiVlhfWmJGUDNkOU12UXBGRThuNzBqdmRZYTpQZ2dnclZKMENieHdZblFPUzUySldCbmJSeU1h';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$keyFile = "/usr/src/myapp/test2.key";
$certFile = "/usr/src/myapp/test2.cer";

curl_setopt($ch, CURLOPT_SSLKEY, $keyFile);
curl_setopt($ch, CURLOPT_SSLCERT, $certFile);
curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_1);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
echo $result
?> 