<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

#ИИН зашил в запросе. Но по-хорошему нужно доставать из процесса регистрации абонента
curl_setopt($ch, CURLOPT_URL, 'https://onlinetest.kisc.kz/identity/1.1.0/verify?iin=880114301129&vendor=3');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

#Путь к отправляему изображению
//$photo = new CURLFile('/usr/src/myapp/1.jpg');

$post = file_get_contents('https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/7d4eb861-1f80-44da-b75e-7f365d0fc3da/280x420');

curl_setopt($ch, CURLOPT_POSTFIELDS, $post);

$headers = array();
$headers[] = 'Authorization: Bearer 17a00568-5ce3-393d-80dd-1e0ba13114c2';
$headers[] = 'Content-Type: image/png';
#Уникальный ключ. Может буть любе число. Генерим сами
$headers[] = 'X-Idempotency-Key: 111995';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$keyFile = "change.key";
$certFile = "certs.crt";

curl_setopt($ch, CURLOPT_SSLKEY, $keyFile);
curl_setopt($ch, CURLOPT_SSLCERT, $certFile);
curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_1);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
echo $result
?>